### PR TITLE
Revert postBuild change

### PR DESCRIPTION
**Pull request by martinRenou**
cc. @fomightez

### CODE REVIEW

**Comment by danielballan** [comment]
Hi @martinRenou, do you understand why this is necessary?

A binder that I have had working in the past bit-rotted at some point, and this PR inspired me to try this fix https://github.com/danielballan/tutorial/commit/e0995e10039aa04cfd221f6e2995425c3558c5d4 which worked, but I do not understand why. I am near certain that consolidating to one build, as shown in linked commit, worked previously.

**Comment by martinRenou** [comment]
Hey,

I cannot find the discussion we had about it @fomightez, but you told me it was not working with the one-step build? I find it odd as well.

> worked previously

Do you mean it was working making the build in one step? I usually do this locally myself and it works like a charm as well. I don't remember why @fomightez was saying it was not working on Binder.

**Comment by danielballan** [comment]
Yes, if I'm not mistaken it was working doing the build in one step on Binder, but it does not work now. It still works for me locally as well.

**Comment by fomightez** [comment]
Here is the discussion I think you were looking for:

https://github.com/matplotlib/ipympl/commit/236f00008892139cfedb1a47fdb61f0e87c4eef7#commitcomment-37935859

No idea though as to why.

**Comment by martinRenou** [comment]
Oh thanks, I was looking for issues and PRs.

Right, so I guess we don't know :confused:

**Pull request merged**
