### PR TITLE
Update galata references

### PR DESCRIPTION
**Pull request by martinRenou**
Please update galata references

cc. @ianthomas23

### CODE REVIEW

**Comment by martinRenou** [comment]
Please update galata references

**Comment by ianthomas23** [comment]
It worked, changing the 2 images that I purposefully make incorrect.

**Comment by martinRenou** [comment]
Unfortunately bot commits do not trigger CI, closing and reopening should run it

**Comment by martinRenou** [comment]
Thanks @ianthomas23 !

**Pull request merged**
