### PR TITLE
Fixup CI

### PR DESCRIPTION
**Pull request by martinRenou**

### CODE REVIEW

**Comment by martinRenou** [comment]
update galata references

**Comment by ianhi** [comment]
is it possible to easily look at the differences in the generated images? I suspect that were catching a styling change in matplotlib latest

**Comment by martinRenou** [comment]
You can download the test artifacts on this page https://github.com/matplotlib/ipympl/actions/runs/4122954626 (bottom of the page -> ui-test-output file). I will contain the expected image, the actual image and the diff.

There seems to be a slight difference in the font rendering of the axis labels.

> I suspect that were catching a styling change in matplotlib latest

Yes, I was thinking the same. It seems to only happen on Ubuntu.

Because it's a very slight difference I tried to change the threshold for the diff, without success.

**Comment by ianhi** [comment]
> Yes, I was thinking the same. It seems to only happen on Ubuntu.

I think that there have been a bunch of changes to the font system recently. I almost wonder if this is surfacing a very subtle bug upstream

**Comment by ianhi** [comment]
@martinRenou what do you think about merging this now and fixing up the ubuntu latest in the future? As it stands this allows us to run tests, which we otherwise cant. which would be helpful for https://github.com/matplotlib/ipympl/pull/517 and https://github.com/matplotlib/ipympl/pull/478

**Comment by martinRenou** [comment]
That's fine with me, half working CI is better than non working one

**Pull request merged**
