### PR TITLE
Handle new FigureCanvasBase.device_pixel_ratio.

### PR DESCRIPTION
**Pull request by QuLogic**
This is a corollary to
https://github.com/matplotlib/matplotlib/pull/19126.

### CODE REVIEW

**Comment by QuLogic** [comment]
There's a `_dpi_ratio` thing in `Canvas`, but I'm not sure if I need to do the same for `_device_pixel_ratio` (as set in `FigureCanvasBase` instead of `FigureCanvasWebAgg`).

**Comment by ianhi** [comment]
Thanks!

This looks safe to merge prior to the the matplotlib PR correct? I think it makes sense to merge this prior to #314

**Comment by QuLogic** [comment]
It should be safe yes, as the new message will just be logged as unknown in older Matplotlib.

**Comment by ianhi** [comment]
> There's a _dpi_ratio thing in Canvas, but I'm not sure if I need to do the same for _device_pixel_ratio (as set in FigureCanvasBase instead of FigureCanvasWebAgg).

That's all the way back from the very first commit https://github.com/matplotlib/ipympl/commit/047ed9551836be1f3a803fd0bc5dce0e10b856be with a comment by   saying: `# Must declare the superclass private members.` @SylvainCorlay you left that comment do you know why they need to be declared? It's not clear to me why we need to transform those into traitlet variables if we aren't syncing them to the frontend.

**Comment by ianhi** [comment]
Actually looking back at https://github.com/matplotlib/ipympl/pull/264 I'm not sure that that comment is still relevant. At the very least nothing bad happened when we removed all those traitlets. 

So in conclusion I don't think you need to change anything more. If anything we could even remove the `_dpi_ratio` being a traitlet.

**Comment by ianhi** [comment]
Thanks!

**Comment by SylvainCorlay** [comment]
Sorry I should have looked into this earlier.

One issue with fetching the device pixel ratio from the front-end (which is what we used to do in the past) is that it may depend on the browser window, so that different views of the same figure would have different values for that property.

**Comment by ianhi** [comment]
> One issue with fetching the device pixel ratio from the front-end (which is what we used to do in the past) 

As far as I can tell that was how ipympl behaved prior to this PR as well. This PR just sends the same information to where it needs to be on the python side for mpl 3.5. 

Is there any way to deal with this? It seems to me that the frontend GUI framework is necessarily the source of truth for this information.

**Comment by SylvainCorlay** [comment]
> As far as I can tell that was how ipympl behaved prior to this PR as well. This PR just sends the same information to where it needs to be on the python side for mpl 3.5.

I thought I removed that logic at some point because of that problem. If I recall correctly, we decided for an arbitrary fixed number (which could be overwritten in the backend).

> Is there any way to deal with this? It seems to me that the frontend GUI framework is necessarily the source of truth for this information.

Setting an arbitrary number may be good enough, since the ipympl front-end isn't really meant for print, pixel-units may be good enough.

**Comment by ianhi** [comment]
> I thought I removed that logic at some point because of that problem. If I recall correctly, we decided for an arbitrary fixed number (which could be overwritten in the backend).

I think this is quantity we are talking about?

https://github.com/matplotlib/ipympl/blob/beec42bd7907e03cacfb1e58884307b24fbd3bb6/js/src/mpl_widget.js#L53


On my monitor at least (not hidpi) this is mostly affected by the zoom level of the jupyterlab tab.

**Comment by SylvainCorlay** [comment]
What I meant is that it is impacted if you open the same notebook with two different computers at the same time. As we are working on live collaboration, this may happen in the near future.

**Comment by SylvainCorlay** [comment]
Note that I am totally fine with keeping this for now, but we may want to keep this issue in mind. A solution could be to completely get rid of that variable.

**Pull request merged**
