### PR TITLE
Fix update_galata_references github action

### PR DESCRIPTION
**Pull request by ianthomas23**
Here I am trying to fix the `update_galata_references` github action after the recent changes that broke it. It should be run as before by adding a PR comment containing the text "update galata references". I have checked in a couple of incorrect test images so that the update is required before CI will pass.

This is not yet using the JupyterLab `maintainer-tools`, that is something to consider in the future.

### CODE REVIEW

**Comment by ianthomas23** [comment]
Please update galata references.

**Comment by ianthomas23** [comment]
Please update galata references.

**Comment by ianthomas23** [comment]
Pretty please update galata references.

**Comment by ianthomas23** [comment]
Hmm, it is running the action from the `main` branch not this PR branch, as it is running code that I have deleted in this branch.

**Comment by martinRenou** [comment]
Yep the bot runs from the main branch. Last time I checked, it's not possible for it to run on the branch that originated the PR.

**Review by martinRenou — APPROVED** [review]
Thank you! Let's merge and test it

**Pull request merged**
